### ISSUE TITLE
Refactor error in `DataType`

### ISSUE THREAD

**Issue by Xuanwo** [apache/paimon-rust#32]
Would you like to perform this refactor? The error type has been defined at https://github.com/apache/paimon-rust/blob/a5cfac79ae4e9eaf87b752b3720fb0575cef3cbb/crates/paimon/src/error.rs#L25-L40

_Originally posted by @Xuanwo in https://github.com/apache/paimon-rust/pull/29#discussion_r1701900349_

**Comment by XuQianJin-Stars** [comment]
I will try to implement this.

**Comment by Xuanwo** [comment]
> I will try to implement this.

That's will be great!
