### ISSUE TITLE
spec: Implement Snapshot

### ISSUE THREAD

**Issue by Xuanwo** [apache/paimon-rust#6]
https://paimon.apache.org/docs/master/concepts/specification/

May need refer to java impl since the spec is not clear.

**Comment by Xuanwo** [comment]
@QuakeWang is willing to do this

**Comment by QuakeWang** [comment]
> https://paimon.apache.org/docs/master/concepts/specification/
> 
> May need refer to java impl since the spec is not clear.

Thanks @Xuanwo , I have got it, and  I will submit a PR recently.
